server:
  servlet:
    context-path: /
  port: 8080
  http2:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false
spring:
  main:
    banner-mode: 'off'
  application:
    name: api-usuarios
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non-null
    serialization:
      write-empty-json-arrays: false
#  datasource:
#    url: jdbc:h2:mem:usuariodb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
  datasource:
    url: jdbc:hsqldb:mem:usuariodb;DB_CLOSE_DELAY=-1
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: h2      
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC
#  h2:
#     console.enabled: true
#     console:
#      path: /db        
logging:
  register-shutdown-hook: true
  pattern:
    console: '%d %-5level [%thread]  %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    root: INFO
    '[ey.desafio.api.usuarios]': debug
token:
 key: ZL2ZYOcCa0FBijSUVK+77DDwgAw6xHB5NCSSS28CJ/M=
 valid:
  milliseconds: 86400000  # Token válido durante 24 horas
